### ISSUE TITLE
bspc subscribe should exit when the output pipe is closed

### ISSUE THREAD

**Issue by msteen** [baskerville/bspwm#681]
After the consumer of `bspc subscribe` exits it should exit as well. An simple example of this would be:

    bspc subscribe node_focus | { read -n 1; echo 5 }

Right now, for this to exit, two `node_focus` events have to occur. However this is not the expected behavior. As soon as the consumer `{ read -n 1; echo 5 }` exits, there is no point to subscribing and so `bspc subscribe node_focus` ought to exit as well. With the new `--count` option to `bspc subscribe` as introduced in #680 we can now simplify the following:

    N=2
    { bspc subscribe node_focus & echo $!; wait $! } | stdbuf -oL -eL head -n $((N + 1)) | {
      read pid
      while read; do
        echo 5
      done
      kill $pid
    } &

To this, by removing the call to `head`:

    N=2
    { bspc subscribe --count $N node_focus & echo $!; wait $! } | {
      read pid
      while read; do
        echo 5
      done
      kill $pid
    } &

And if this issue is solved, it could be further simplified to just:

    N=2
    bspc subscribe --count $N node_focus | while read; do
      echo 5
    done &

I have not yet had to implement such a thing, so I have no idea what the best approach would be, but wouldn't the simplest solution be to have a signal handler for `SIGPIPE`, but only in the case of `bspc subscribe`?

**Comment by baskerville** [comment]
Relying on `SIGPIPE` won't help, because `SIGPIPE` is only generated when we try to write to `stdout`.

**Comment by msteen** [comment]
Yeah, I see now that it is useless in this case, using it would have resulted in no change of behavior, since it indeed is only generated during the extra event write attempt. I had to lookup some [explanation](http://stefan.buettcher.org/cs/conn_closed.html), but from what I can gather it seems the right approach. Thanks a lot, I will try it tomorrow!

**Comment by baskerville** [comment]
It should work as of 225561a.

**Comment by baskerville** [comment]
Now that I come to think of it, there's something problematic with this approach tough. Suppose that there's a command, `make_window`, that creates a window and I want to wait for the window to be managed by `bspwm`. A naive user would do the following:
```sh
make_window
bspc subscribe -c 1 node_manage
```
But the problem is that there's no guarantee that the `bspc` process will wake `bspwm` before `make_window`. We might miss the `node_manage` event.

What I could do is to add an option to `subscribe` that makes the server writes the events to a FIFO. The call to `bspc` will then print the FIFO's path and return:
```sh
RSP_CHAN=$(bspc subscribe -f -c 1 node_manage)
make_window
< "$RSP_CHAN"
```

**Comment by baskerville** [comment]
I've implemented the FIFO feature in 9ea4b01.

Here's an example using the aforementioned technique:
```sh
#! /bin/sh

count=13
rsp_chan=$(bspc subscribe -f -c "$count" node_add)

while [ $count -gt 0 ] ; do
	xterm &
	count=$((count - 1))
done

wc -l "$rsp_chan"
```
The output of the above script should be `13` (followed by the FIFO path).

**Comment by msteen** [comment]
I fail to see how using a FIFO fixes anything. The example you gave:

    make_window &
    bspc subscribe -c 1 node_manage

It can fail because it could take longer for `bspwm` to start the subscription than for the window to be created. How does using a FIFO address this? Isn't the only thing that changes that it then writes to a FIFO instead of stdout? Take this example:

    make_window &
    rsp_chan=$(bspc subscribe -f -c 1 node_manage)
    # Do something with $rsp_chan

Would this still not potentially fail to see the window creation from happening? In other words, is how events are processed not irrelevant to the actual problem of that the timing could be off causing some events to be missed?

Just looking at the source code, is what you implemented not just the same doing this yourself in the shell:

    count=3
    BSPC_SUB_FIFO="$XDG_RUNTIME_DIR/bspc-sub.fifo"
    [ -e "$BSPC_SUB_FIFO" ] || mkfifo "$BSPC_SUB_FIFO"
    bspc subscribe -c "$count" node_manage > "$BSPC_SUB_FIFO" &

    while [ $count -gt 0 ] ; do
      xterm &
      count=$((count - 1))
    done

    wc -l "$BSPC_SUB_FIFO" # output = 3 /run/user/1000/bspc-sub.fifo

Or is your FIFO implementation somehow more immediate, while the default socket implementation could have some lag? In that case you can ignore all this.

**Comment by baskerville** [comment]
The difference is that `bspc subscribe -f ...` doesn't block (it prints the FIFO's path). And when it returns, the subscriber and the FIFO are ready.

That's why we can call it **before** `xterm &`.

**Comment by msteen** [comment]
That indeed would ensure there are not timing issues, thanks for clearing that up. However it does not address your initial example of the naive user (subscription **after** window creation). That example might still fail, but I cannot think of anyway that you could fix that situation without potentially creating other issues in the process. For example you could log events whether they are subscribed or not, and once a subscription is requested, you could use that log to send the events of some time window. That could fix the naive example, but if you make this time window too big, you might handle events that should no longer be relevant.

**Comment by baskerville** [comment]
`subscribe -f` is a simple way of fixing the problem raised by the naive example.

But the naive example itself can't be fixed. We could store events and deliver the missed ones to a newly born subscriber: but how would we identify the past events we need to deliver if we don't have a time frame?

**Comment by msteen** [comment]
Hence me saying that I cannot think of any way that could fix the situation without also have problems themselves, and me talking about the problems of using a time frame might produce. It was just some brainstorming of potential solutions. The biggest problem with the idea I came up with is indeed how to get the right time frame. One approach would be to use `/proc` to determine the start time of the start time of the shell that called `bspc subscribe` and then use the time between the start time of the shell and the start time of `bspc subscribe` as the time frame. But it is just a suggestion, if you don't like it, just forget about it. Maybe just updating the documentation to warn about the naive example is enough.
