### ISSUE TITLE
`bspc quit` doesn't do anything

### ISSUE THREAD

**Issue by VoidNoire** [baskerville/bspwm#834]
It used to work, but now it doesn't and I'm not sure what caused it to stop working. Switching to the TTY `bspwm` was launched from shows `Failed to connect to socket`. I can provide more logs, but I don't know how to produce them.

**Comment by baskerville** [comment]
The easiest (and maybe the only) way of getting this error message is to run `bspc` while `bspwm` isn't running.

**Comment by VoidNoire** [comment]
It's definitely running. I'm using it right now and it's listed in the output of `top`. Just to clarify, I only see that message after I run `bspc quit` twice (and every other time after the second). Also, I made an error in my first post: The message appears in the terminal inside `bspwm`, not in the TTY `bspwm` was launched from.
![img_20180827_175543](https://user-images.githubusercontent.com/18732253/44673134-2ddb0480-aa1a-11e8-9ef3-ab267f9bbf7f.jpg)

**Comment by baskerville** [comment]
> It's definitely running. I'm using it right now and it's listed in the output of `top`.

Can you run any other `bspc` command after the first failure?

> Just to clarify, I only see that message after I run `bspc quit` twice (and every other time after the second).

Are you running `bspwm` inside a loop?

What's the output of `ls /tmp/bspwm*-socket` before and after each `bspc quit` calls?

Does the output of `pidof bspwm` changes before and after the first `bspc quit` call?

**Comment by VoidNoire** [comment]
Ok, here's the commands and their outputs:

```
a:~# ls /tmp/bspwm*-socket
srwxrwx--- 0 a 27 Aug 19:53 /tmp/bspwm_0_0-socket
a:~# pidof bspwm
11716
a:~# bspc quit
a:~# ls /tmp/bspwm*-socket
"/tmp/bspwm*-socket": No such file or directory (os error 2)
a:~# pidof bspwm
a:~#
```
At this point, I'm no longer able to change workspace with `super + {1-9}`,  so I guess bspc stops working.  In fact,  entering `bspc ^{2}` results in the output:

`Failed to connect to the socket.`

Every subsequent `bspc quit` causes the commands to output:

```
Failed to connect to the socket.
a:~# ls /tmp/bspwm*-socket
"/tmp/bspwm*-socket": No such file or directory (os error 2)
a:~# pidof bspwm
a:~#
```

**Comment by baskerville** [comment]
Right, so the `bspwm` process is actually not running after `bspc quit`: it becomes a zombie.

The problem might come from the parent process (the PPID is probably in the fourth column in the output of  `ps l`?) or from the children (`pgrep -l -P $(pgrep bspwm)`).

**Comment by VoidNoire** [comment]
Well here are the outputs:
```
a:~# ps l
F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
4  1000   701   666  20   0  26988 12392 -      Ssl  tty1       0:00 -ion
0  1000   748   701  20   0   4376  1520 -      S+   tty1       0:00 /bin/sh /bin/startx
0  1000   812   748  20   0  16012  1056 -      S+   tty1       0:00 xinit /home/a/.xinitrc -- /etc/X11/xinit/xserverrc :0 -auth /tmp/server
0  1000   868   812  20   0 273708 21860 -      Sl   tty1       0:00 xfce4-panel
0  1000   872   868  20   0      0     0 -      Z    tty1       0:00 [xsetroot] <defunct>
0  1000   873   868  20   0      0     0 -      Z    tty1       0:00 [setxkbmap] <defunct>
0  1000   874   868  20   0  23244  1220 -      S    tty1       0:00 bspwm
0  1000   875   868  20   0      0     0 -      Z    tty1       0:00 [alacritty] <defunct>
1  1000   913     1  20   0  22840  2128 -      S    tty1       0:00 dbus-launch --autolaunch a01cce855a7cb410c9e8b2ef5b6cccb6 --binary-synt
0  1000   967   868  20   0 199548 21692 -      S    tty1       0:00 /usr/lib/xfce4/panel/wrapper-2.0 /usr/lib/xfce4/panel/plugins/libbatter
0  1000   969   868  20   0 181680 14000 -      S    tty1       0:00 /usr/lib/xfce4/panel/wrapper-1.0 /usr/lib/xfce4/panel/plugins/libsystra
0  1000   970   868  20   0 186000 17648 -      S    tty1       0:00 /usr/lib/xfce4/panel/wrapper-1.0 /usr/lib/xfce4/panel/plugins/libaction
0  1000  1402  1392  20   0  26988 10552 -      Ssl  pts/1      0:00 /home/a/.cargo/bin/ion
4  1000  1426  1402  20   0   9188   952 -      R+   pts/1      0:00 ps l
a:~# pgrep -l -P $(pgrep bspwm)
a:~# bspc quit
a:~# ps l
F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
4  1000   701   666  20   0  26988 12392 -      Ssl  tty1       0:00 -ion
0  1000   748   701  20   0   4376  1520 -      S+   tty1       0:00 /bin/sh /bin/startx
0  1000   812   748  20   0  16012  1056 -      S+   tty1       0:00 xinit /home/a/.xinitrc -- /etc/X11/xinit/xserverrc :0 -auth /tmp/server
0  1000   868   812  20   0 273708 21860 -      Sl   tty1       0:00 xfce4-panel
0  1000   872   868  20   0      0     0 -      Z    tty1       0:00 [xsetroot] <defunct>
0  1000   873   868  20   0      0     0 -      Z    tty1       0:00 [setxkbmap] <defunct>
0  1000   874   868  20   0      0     0 -      Z    tty1       0:00 [bspwm] <defunct>
0  1000   875   868  20   0      0     0 -      Z    tty1       0:00 [alacritty] <defunct>
1  1000   913     1  20   0  22840  2128 -      S    tty1       0:00 dbus-launch --autolaunch a01cce855a7cb410c9e8b2ef5b6cccb6 --binary-synt
0  1000   967   868  20   0 199548 21692 -      S    tty1       0:00 /usr/lib/xfce4/panel/wrapper-2.0 /usr/lib/xfce4/panel/plugins/libbatter
0  1000   969   868  20   0 181680 14000 -      S    tty1       0:00 /usr/lib/xfce4/panel/wrapper-1.0 /usr/lib/xfce4/panel/plugins/libsystra
0  1000   970   868  20   0 186000 17648 -      S    tty1       0:00 /usr/lib/xfce4/panel/wrapper-1.0 /usr/lib/xfce4/panel/plugins/libaction
0  1000  1402  1392  20   0  26988 12660 -      Ssl  pts/1      0:00 /home/a/.cargo/bin/ion
4  1000  1529  1402  20   0   9188  1012 -      R+   pts/1      0:00 ps l
a:~# pgrep -l -P $(pgrep bspwm)
a:~#
```

**Comment by msteen** [comment]
Personally I had the problem that when I exited `bpswm`, it would also kill the programs I started in `bspwmrc`, including e.g. my browser, which I wanted `bspwm` to reuse on restart.

I fixed that problem by doing a double fork, disconnecting those programs from the `bspwmrc` script. And when `bspwmrc` ran again, I did not want it to start e.g. another browser process, so I also made sure to only run the long living programs only once. So I have been using the following:
```bash
# Some commands get expanded in the process list, others not,
# so we equate this by explicitly expanding them all before calling them.
function already_spawned() {
  pgrep -cfx "$*" > /dev/null 2>&1 || {
    set -- $(command -v "$1") "${@:2}"
    pgrep -cfx "$*" > /dev/null 2>&1
  }
}

function spawn_once() {
  if ! already_spawned "$@"; then
    # https://superuser.com/questions/172043/how-do-i-fork-a-process-that-doesnt-die-when-shell-exits/172476#172476
    ( setsid "$@" & )
  fi
}
```

Now I do not know how you start `bspwm`, so I do not know if the above script will be helpful to you, but considering you want to quit `bspwm`, I assume you want to restart it again at some point, and then you probably will run in the same problem I did for certain programs. And if not, if you just want to kill it and not restart it afterwards, it might still be useful to solve the zombie problem, depending on how you start `bspwm`. From the process tree it looks like `xfce-panel` starts them, or at least takes ownership at some point. Personally I just use the following in my window manager script:
```bash
while bspwm; do :; done
```

In that script `bspwm` will die off properly and be restarted due to the repeat loop. Here you should definitely not double fork, otherwise the loop condition will not block.

**Comment by VoidNoire** [comment]
@msteen that seems useful, thanks. in any case, the relevant section in my `.xinitrc` is:
```sh
xsetroot -cursor_name left_ptr -solid "#000000" &
setxkbmap -layout gb &
exec bspwm &
# run another window, alacritty, before xfce4-panel to prevent xfce4-panel from being behind other windows
exec alacritty &
exec xfce4-panel
```

**Comment by msteen** [comment]
Why use `exec` to start your programs? Doing what you do makes it so that `xfce4-panel` replaces the shell of the script and thus takes ownership of the background programs started within it, including `bspwm`. Removing `exec` from your script should fix your problem.

For more information on `exec`, there is plenty to be found, for example:
http://wiki.bash-hackers.org/commands/builtin/exec

**Comment by VoidNoire** [comment]
@msteen thanks for the suggestion. i tried removing all occurrences of `exec` in the section but unfortunately the outcome is still the same.

**Comment by spartan117au** [comment]
I also get this issue. It happens seemingly randomly upon screen going to sleep or waking from suspend. bspc wm -r seems to restore functionality, but very annoying nonetheless.
